version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: atm-postgres
    restart: always

    environment:
      POSTGRES_DB: atm_db
      POSTGRES_USER: atm_user
      POSTGRES_PASSWORD: atm_pass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    networks:
      atm-network:
        ipv4_address: 172.20.0.2

  monitoring-app:
    build: .
    container_name: atm-monitoring-app
    restart: always

    depends_on:
      - postgres
    
    ports:
      - "9000:9000"
    
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/atm_db
      SPRING_DATASOURCE_USERNAME: atm_user
      SPRING_DATASOURCE_PASSWORD: atm_pass
    
    networks:
      - atm-network

volumes:
  postgres_data:

networks:
  atm-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16