spring:
  application:
    name: monitoring-app

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/atm_db}
    username: ${SPRING_DATASOURCE_USERNAME:atm_user}
    password: ${SPRING_DATASOURCE_PASSWORD:atm_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always 
    
server:
  port: 9000

jwt:
  secret: ${JWT_SECRET:bXktc3VwZXItc2VjcmV0LWtleS1mb3ItYXRtLW1vbml0b3JpbmctYXBwLTEyMzQ1Njc4OTAxMjM0NTY=}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:5000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:10000}
